/*
 * SPDX-FileCopyrightText: © 2020 Liferay, Inc. <https://liferay.com>
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */

import handleFieldAdded from '../../../../../src/main/resources/META-INF/resources/js/components/LayoutProvider/handlers/fieldAddedHandler.es';
import handleFieldEdited from '../../../../../src/main/resources/META-INF/resources/js/components/LayoutProvider/handlers/fieldEditedHandler.es';
import handleFocusedFieldEvaluationEnded from '../../../../../src/main/resources/META-INF/resources/js/components/LayoutProvider/handlers/focusedFieldEvaluationEndedHandler.es';
import {shouldAutoGenerateName} from '../../../../../src/main/resources/META-INF/resources/js/components/LayoutProvider/util/defaults.es';
import {generateFieldName} from '../../../../../src/main/resources/META-INF/resources/js/components/LayoutProvider/util/fields.es';
import * as settingsContextUtil from '../../../../../src/main/resources/META-INF/resources/js/components/LayoutProvider/util/settingsContext.es';
import mockFieldTypes from '../../../__mock__/mockFieldTypes.es';

describe('LayoutProvider/handlers/focusedFieldEvaluationEndedHandler', () => {
	describe('focusedFieldEvaluationEnded(props, state, event)', () => {
		it('does not autogenerate field name', () => {
			let state = {
				focusedField: {},
				pages: [{rows: [{columns: [{fields: []}]}]}],
				rules: [],
			};

			const props = {
				defaultLanguageId: 'en_US',
				editingLanguageId: 'en_US',
				fieldNameGenerator: (desiredName, currentName) => {
					const {pages} = state;

					return generateFieldName(pages, desiredName, currentName);
				},
				shouldAutoGenerateName,
			};

			// Adds a field

			state = handleFieldAdded(props, state, {
				data: {},
				fieldType: mockFieldTypes[0],
				indexes: {
					columnIndex: 0,
					pageIndex: 0,
					rowIndex: 0,
				},
			});

			// Edits the field name

			state = handleFieldEdited(props, state, {
				propertyName: 'name',
				propertyValue: 'foo2',
			});

			// Edits the field label (without allowing the name to be autogenerated)

			state = handleFieldEdited(
				{
					...props,
					shouldAutoGenerateName: () => false,
				},
				state,
				{
					propertyName: 'label',
					propertyValue: 'foo',
				}
			);

			// Simulates an evaluation result

			state = handleFocusedFieldEvaluationEnded(
				props,
				state,
				state.focusedField.settingsContext
			);

			// Asserts name was not updated

			expect(state.focusedField.fieldName).toEqual('foo2');
			expect(
				settingsContextUtil.getSettingsContextProperty(
					state.focusedField.settingsContext,
					'name'
				)
			).toEqual('foo2');
		});
	});
});
