/*
 * SPDX-FileCopyrightText: © 2019 Liferay, Inc. <https://liferay.com>
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */

package com.liferay.portal.tools.service.builder.test.uad.anonymizer;

import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.tools.service.builder.test.model.UADPartialEntry;
import com.liferay.portal.tools.service.builder.test.service.UADPartialEntryLocalService;
import com.liferay.portal.tools.service.builder.test.uad.constants.SBTestUADConstants;
import com.liferay.user.associated.data.anonymizer.DynamicQueryUADAnonymizer;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the uad partial entry UAD anonymizer.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link UADPartialEntryUADAnonymizer}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseUADPartialEntryUADAnonymizer
	extends DynamicQueryUADAnonymizer<UADPartialEntry> {

	@Override
	public void autoAnonymize(
			UADPartialEntry uadPartialEntry, long userId, User anonymousUser)
		throws PortalException {

		if (uadPartialEntry.getUserId() == userId) {
			uadPartialEntry.setUserId(anonymousUser.getUserId());
			uadPartialEntry.setUserName(anonymousUser.getFullName());
		}

		uadPartialEntryLocalService.updateUADPartialEntry(uadPartialEntry);
	}

	@Override
	public void delete(UADPartialEntry uadPartialEntry) throws PortalException {
		uadPartialEntryLocalService.deleteUADPartialEntry(uadPartialEntry);
	}

	@Override
	public Class<UADPartialEntry> getTypeClass() {
		return UADPartialEntry.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return uadPartialEntryLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return SBTestUADConstants.USER_ID_FIELD_NAMES_UAD_PARTIAL_ENTRY;
	}

	@Reference
	protected UADPartialEntryLocalService uadPartialEntryLocalService;

}