/*
 * SPDX-FileCopyrightText: © 2019 Liferay, Inc. <https://liferay.com>
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */

package com.liferay.portal.uad.anonymizer;

import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.RepositoryEntry;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.service.RepositoryEntryLocalService;
import com.liferay.portal.uad.constants.PortalUADConstants;
import com.liferay.user.associated.data.anonymizer.DynamicQueryUADAnonymizer;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the repository entry UAD anonymizer.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link RepositoryEntryUADAnonymizer}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseRepositoryEntryUADAnonymizer
	extends DynamicQueryUADAnonymizer<RepositoryEntry> {

	@Override
	public void autoAnonymize(
			RepositoryEntry repositoryEntry, long userId, User anonymousUser)
		throws PortalException {

		if (repositoryEntry.getUserId() == userId) {
			repositoryEntry.setUserId(anonymousUser.getUserId());
			repositoryEntry.setUserName(anonymousUser.getFullName());
		}

		repositoryEntryLocalService.updateRepositoryEntry(repositoryEntry);
	}

	@Override
	public void delete(RepositoryEntry repositoryEntry) throws PortalException {
		repositoryEntryLocalService.deleteRepositoryEntry(repositoryEntry);
	}

	@Override
	public Class<RepositoryEntry> getTypeClass() {
		return RepositoryEntry.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return repositoryEntryLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return PortalUADConstants.USER_ID_FIELD_NAMES_REPOSITORY_ENTRY;
	}

	@Reference
	protected RepositoryEntryLocalService repositoryEntryLocalService;

}