/*
 * SPDX-FileCopyrightText: © 2019 Liferay, Inc. <https://liferay.com>
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */

package com.liferay.users.admin.uad.anonymizer;

import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.UserTracker;
import com.liferay.portal.kernel.service.UserTrackerLocalService;
import com.liferay.user.associated.data.anonymizer.DynamicQueryUADAnonymizer;
import com.liferay.users.admin.uad.constants.UsersAdminUADConstants;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the user tracker UAD anonymizer.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link UserTrackerUADAnonymizer}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseUserTrackerUADAnonymizer
	extends DynamicQueryUADAnonymizer<UserTracker> {

	@Override
	public void autoAnonymize(
			UserTracker userTracker, long userId, User anonymousUser)
		throws PortalException {

		if (userTracker.getUserId() == userId) {
			delete(userTracker);
		}
	}

	@Override
	public void delete(UserTracker userTracker) throws PortalException {
		userTrackerLocalService.deleteUserTracker(userTracker);
	}

	@Override
	public Class<UserTracker> getTypeClass() {
		return UserTracker.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return userTrackerLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return UsersAdminUADConstants.USER_ID_FIELD_NAMES_USER_TRACKER;
	}

	@Reference
	protected UserTrackerLocalService userTrackerLocalService;

}