/*
 * SPDX-FileCopyrightText: © 2020 Liferay, Inc. <https://liferay.com>
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */

package com.liferay.dynamic.data.mapping.uad.anonymizer;

import com.liferay.dynamic.data.mapping.model.DDMFormInstance;
import com.liferay.dynamic.data.mapping.service.DDMFormInstanceLocalService;
import com.liferay.dynamic.data.mapping.uad.constants.DDMUADConstants;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.User;
import com.liferay.user.associated.data.anonymizer.DynamicQueryUADAnonymizer;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the ddm form instance UAD anonymizer.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link DDMFormInstanceUADAnonymizer}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseDDMFormInstanceUADAnonymizer
	extends DynamicQueryUADAnonymizer<DDMFormInstance> {

	@Override
	public void autoAnonymize(
			DDMFormInstance ddmFormInstance, long userId, User anonymousUser)
		throws PortalException {

		if (ddmFormInstance.getUserId() == userId) {
			ddmFormInstance.setUserId(anonymousUser.getUserId());
			ddmFormInstance.setUserName(anonymousUser.getFullName());
		}

		if (ddmFormInstance.getVersionUserId() == userId) {
			ddmFormInstance.setVersionUserId(anonymousUser.getUserId());
			ddmFormInstance.setVersionUserName(anonymousUser.getFullName());
		}

		ddmFormInstanceLocalService.updateDDMFormInstance(ddmFormInstance);
	}

	@Override
	public void delete(DDMFormInstance ddmFormInstance) throws PortalException {
		ddmFormInstanceLocalService.deleteFormInstance(ddmFormInstance);
	}

	@Override
	public Class<DDMFormInstance> getTypeClass() {
		return DDMFormInstance.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return ddmFormInstanceLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return DDMUADConstants.USER_ID_FIELD_NAMES_DDM_FORM_INSTANCE;
	}

	@Reference
	protected DDMFormInstanceLocalService ddmFormInstanceLocalService;

}