/*
 * SPDX-FileCopyrightText: © 2020 Liferay, Inc. <https://liferay.com>
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */

export const ADD_FRAGMENT_COMPOSITION = 'ADD_FRAGMENT_COMPOSITION';
export const ADD_FRAGMENT_ENTRY_LINKS = 'ADD_FRAGMENT_ENTRY_LINKS';
export const ADD_FRAGMENT_ENTRY_LINK_COMMENT =
	'ADD_FRAGMENT_ENTRY_LINK_COMMENT';
export const ADD_MAPPED_INFO_ITEM = 'ADD_MAPPED_INFO_ITEM';
export const CREATE_COLUMN = 'CREATE_COLUMN';
export const DELETE_FRAGMENT_ENTRY_LINK_COMMENT =
	'DELETE_FRAGMENT_ENTRY_LINK_COMMENT';
export const DELETE_WIDGETS = 'DELETE_WIDGETS';
export const EDIT_FRAGMENT_ENTRY_LINK_COMMENT =
	'EDIT_FRAGMENT_ENTRY_LINK_COMMENT';
export const LOAD_REDUCER = 'LOAD_REDUCER';
export const MOVE_ITEM = 'MOVE_ITEM';
export const REMOVE_COLUMN = 'REMOVE_COLUMN';
export const SWITCH_SIDEBAR_PANEL = 'SWITCH_SIDEBAR_PANEL';
export const SWITCH_VIEWPORT_SIZE = 'SWITCH_VIEWPORT_SIZE';
export const TOGGLE_PERMISSION = 'TOGGLE_PERMISSION';
export const TOGGLE_SHOW_RESOLVED_COMMENTS = 'TOGGLE_SHOW_RESOLVED_COMMENTS';
export const UNLOAD_REDUCER = 'UNLOAD_REDUCER';
export const UPDATE_COL_SIZE = 'UPDATE_COL_SIZE';
export const UPDATE_EDITABLE_VALUES = 'UPDATE_EDITABLE_VALUES';
export const UPDATE_FRAGMENT_ENTRY_LINK_CONFIGURATION =
	'UPDATE_FRAGMENT_ENTRY_LINK_CONFIGURATION';
export const UPDATE_FRAGMENT_ENTRY_LINK_CONTENT =
	'UPDATE_FRAGMENT_ENTRY_LINK_CONTENT';
export const UPDATE_LANGUAGE_ID = 'UPDATE_LANGUAGE_ID';
export const UPDATE_LAYOUT_DATA = 'UPDATE_LAYOUT_DATA';
export const UPDATE_NETWORK = 'UPDATE_NETWORK';
export const UPDATE_PAGE_CONTENTS = 'UPDATE_PAGE_CONTENTS';
