/*
 * SPDX-FileCopyrightText: © 2019 Liferay, Inc. <https://liferay.com>
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */

package com.liferay.layout.uad.anonymizer;

import com.liferay.layout.uad.constants.LayoutUADConstants;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.LayoutSetPrototype;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.service.LayoutSetPrototypeLocalService;
import com.liferay.user.associated.data.anonymizer.DynamicQueryUADAnonymizer;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the layout set prototype UAD anonymizer.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link LayoutSetPrototypeUADAnonymizer}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseLayoutSetPrototypeUADAnonymizer
	extends DynamicQueryUADAnonymizer<LayoutSetPrototype> {

	@Override
	public void autoAnonymize(
			LayoutSetPrototype layoutSetPrototype, long userId,
			User anonymousUser)
		throws PortalException {

		if (layoutSetPrototype.getUserId() == userId) {
			layoutSetPrototype.setUserId(anonymousUser.getUserId());
			layoutSetPrototype.setUserName(anonymousUser.getFullName());
		}

		layoutSetPrototypeLocalService.updateLayoutSetPrototype(
			layoutSetPrototype);
	}

	@Override
	public void delete(LayoutSetPrototype layoutSetPrototype)
		throws PortalException {

		layoutSetPrototypeLocalService.deleteLayoutSetPrototype(
			layoutSetPrototype);
	}

	@Override
	public Class<LayoutSetPrototype> getTypeClass() {
		return LayoutSetPrototype.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return layoutSetPrototypeLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return LayoutUADConstants.USER_ID_FIELD_NAMES_LAYOUT_SET_PROTOTYPE;
	}

	@Reference
	protected LayoutSetPrototypeLocalService layoutSetPrototypeLocalService;

}