/*
 * SPDX-FileCopyrightText: © 2019 Liferay, Inc. <https://liferay.com>
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */

package com.liferay.layout.uad.anonymizer;

import com.liferay.layout.uad.constants.LayoutUADConstants;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.LayoutFriendlyURL;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.service.LayoutFriendlyURLLocalService;
import com.liferay.user.associated.data.anonymizer.DynamicQueryUADAnonymizer;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the layout friendly url UAD anonymizer.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link LayoutFriendlyURLUADAnonymizer}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseLayoutFriendlyURLUADAnonymizer
	extends DynamicQueryUADAnonymizer<LayoutFriendlyURL> {

	@Override
	public void autoAnonymize(
			LayoutFriendlyURL layoutFriendlyURL, long userId,
			User anonymousUser)
		throws PortalException {

		if (layoutFriendlyURL.getUserId() == userId) {
			layoutFriendlyURL.setUserId(anonymousUser.getUserId());
			layoutFriendlyURL.setUserName(anonymousUser.getFullName());
		}

		layoutFriendlyURLLocalService.updateLayoutFriendlyURL(
			layoutFriendlyURL);
	}

	@Override
	public void delete(LayoutFriendlyURL layoutFriendlyURL)
		throws PortalException {

		layoutFriendlyURLLocalService.deleteLayoutFriendlyURL(
			layoutFriendlyURL);
	}

	@Override
	public Class<LayoutFriendlyURL> getTypeClass() {
		return LayoutFriendlyURL.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return layoutFriendlyURLLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return LayoutUADConstants.USER_ID_FIELD_NAMES_LAYOUT_FRIENDLY_URL;
	}

	@Reference
	protected LayoutFriendlyURLLocalService layoutFriendlyURLLocalService;

}