/*
 * SPDX-FileCopyrightText: © 2019 Liferay, Inc. <https://liferay.com>
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */

package com.liferay.layout.uad.anonymizer;

import com.liferay.layout.uad.constants.LayoutUADConstants;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.LayoutRevision;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.service.LayoutRevisionLocalService;
import com.liferay.user.associated.data.anonymizer.DynamicQueryUADAnonymizer;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the layout revision UAD anonymizer.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link LayoutRevisionUADAnonymizer}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseLayoutRevisionUADAnonymizer
	extends DynamicQueryUADAnonymizer<LayoutRevision> {

	@Override
	public void autoAnonymize(
			LayoutRevision layoutRevision, long userId, User anonymousUser)
		throws PortalException {

		if (layoutRevision.getUserId() == userId) {
			layoutRevision.setUserId(anonymousUser.getUserId());
			layoutRevision.setUserName(anonymousUser.getFullName());
		}

		if (layoutRevision.getStatusByUserId() == userId) {
			layoutRevision.setStatusByUserId(anonymousUser.getUserId());
			layoutRevision.setStatusByUserName(anonymousUser.getFullName());
		}

		layoutRevisionLocalService.updateLayoutRevision(layoutRevision);
	}

	@Override
	public void delete(LayoutRevision layoutRevision) throws PortalException {
		layoutRevisionLocalService.deleteLayoutRevision(layoutRevision);
	}

	@Override
	public Class<LayoutRevision> getTypeClass() {
		return LayoutRevision.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return layoutRevisionLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return LayoutUADConstants.USER_ID_FIELD_NAMES_LAYOUT_REVISION;
	}

	@Reference
	protected LayoutRevisionLocalService layoutRevisionLocalService;

}