/*
 * SPDX-FileCopyrightText: © 2020 Liferay, Inc. <https://liferay.com>
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */

package com.liferay.portal.tools.service.builder.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.sql.Blob;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EagerBlobEntity service. Represents a row in the &quot;EagerBlobEntity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.model.impl.EagerBlobEntityModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.model.impl.EagerBlobEntityImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EagerBlobEntity
 * @generated
 */
@ProviderType
public interface EagerBlobEntityModel extends BaseModel<EagerBlobEntity> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a eager blob entity model instance should use the {@link EagerBlobEntity} interface instead.
	 */

	/**
	 * Returns the primary key of this eager blob entity.
	 *
	 * @return the primary key of this eager blob entity
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this eager blob entity.
	 *
	 * @param primaryKey the primary key of this eager blob entity
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this eager blob entity.
	 *
	 * @return the uuid of this eager blob entity
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this eager blob entity.
	 *
	 * @param uuid the uuid of this eager blob entity
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the eager blob entity ID of this eager blob entity.
	 *
	 * @return the eager blob entity ID of this eager blob entity
	 */
	public long getEagerBlobEntityId();

	/**
	 * Sets the eager blob entity ID of this eager blob entity.
	 *
	 * @param eagerBlobEntityId the eager blob entity ID of this eager blob entity
	 */
	public void setEagerBlobEntityId(long eagerBlobEntityId);

	/**
	 * Returns the group ID of this eager blob entity.
	 *
	 * @return the group ID of this eager blob entity
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this eager blob entity.
	 *
	 * @param groupId the group ID of this eager blob entity
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the blob of this eager blob entity.
	 *
	 * @return the blob of this eager blob entity
	 */
	public Blob getBlob();

	/**
	 * Sets the blob of this eager blob entity.
	 *
	 * @param blob the blob of this eager blob entity
	 */
	public void setBlob(Blob blob);

}