/*
 * SPDX-FileCopyrightText: © 2020 Liferay, Inc. <https://liferay.com>
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */

export const CREATE_SEGMENTS_EXPERIENCE = 'CREATE_SEGMENTS_EXPERIENCE';
export const SELECT_SEGMENTS_EXPERIENCE = 'SELECT_SEGMENTS_EXPERIENCE';
export const DELETE_SEGMENTS_EXPERIENCE = 'DELETE_SEGMENTS_EXPERIENCE';
export const UPDATE_SEGMENTS_EXPERIENCE = 'UPDATE_SEGMENTS_EXPERIENCE';
export const UPDATE_SEGMENTS_EXPERIENCE_PRIORITY =
	'UPDATE_SEGMENTS_EXPERIENCE_PRIORITY';
