/*
 * SPDX-FileCopyrightText: © 2019 Liferay, Inc. <https://liferay.com>
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */

package com.liferay.adaptive.media.image.finder;

import com.liferay.adaptive.media.finder.AMFinder;
import com.liferay.adaptive.media.image.processor.AMImageProcessor;
import com.liferay.portal.kernel.repository.model.FileVersion;

/**
 * Provides a specialized interface for locating {@link
 * com.liferay.adaptive.media.AdaptiveMedia} specific {@link FileVersion} models
 * generated by {@link AMImageProcessor}s. Implementations must accept queries
 * generated by {@link AMImageQueryBuilder} instances.
 *
 * @author Adolfo Pérez
 */
public interface AMImageFinder
	extends AMFinder<AMImageQueryBuilder, FileVersion, AMImageProcessor> {
}