/*
 * SPDX-FileCopyrightText: © 2020 Liferay, Inc. <https://liferay.com>
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.portal.tools.service.builder.test.model.EagerBlobEntity;
import com.liferay.portal.tools.service.builder.test.service.EagerBlobEntityLocalServiceUtil;

/**
 * The extended model base implementation for the EagerBlobEntity service. Represents a row in the &quot;EagerBlobEntity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EagerBlobEntityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EagerBlobEntityImpl
 * @see EagerBlobEntity
 * @generated
 */
public abstract class EagerBlobEntityBaseImpl
	extends EagerBlobEntityModelImpl implements EagerBlobEntity {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a eager blob entity model instance should use the <code>EagerBlobEntity</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			EagerBlobEntityLocalServiceUtil.addEagerBlobEntity(this);
		}
		else {
			EagerBlobEntityLocalServiceUtil.updateEagerBlobEntity(this);
		}
	}

}