/*
 * SPDX-FileCopyrightText: © 2020 Liferay, Inc. <https://liferay.com>
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.portal.tools.service.builder.test.model.LazyBlobEntity;
import com.liferay.portal.tools.service.builder.test.service.LazyBlobEntityLocalServiceUtil;

/**
 * The extended model base implementation for the LazyBlobEntity service. Represents a row in the &quot;LazyBlobEntity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LazyBlobEntityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LazyBlobEntityImpl
 * @see LazyBlobEntity
 * @generated
 */
public abstract class LazyBlobEntityBaseImpl
	extends LazyBlobEntityModelImpl implements LazyBlobEntity {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a lazy blob entity model instance should use the <code>LazyBlobEntity</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			LazyBlobEntityLocalServiceUtil.addLazyBlobEntity(this);
		}
		else {
			LazyBlobEntityLocalServiceUtil.updateLazyBlobEntity(this);
		}
	}

}